sudo: required
services:
  - docker

before_install:
  - docker build -t prodApp -f Dockerfile.dev .

script:
  - docker run -e CI=true prodApp npm run test


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "ap-northeast-1"
  app: "dockerProdApp"
  env: "Dockerprodapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-631133471327"
  bucket_path: "dockerProdApp"
  on:
    branch: main